/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.GUI;

import br.ufrn.services.AtualizaMonitor;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Zeff
 */
public class MonitorCidade extends javax.swing.JFrame implements AtualizaMonitor {

    /**
     * Creates new form MonitorCidade
     */
    private static final MonitorCidade MONITOR_CIDADE = new MonitorCidade();

    public static MonitorCidade getInstance() {
        MONITOR_CIDADE.setVisible(true);
        return MONITOR_CIDADE;
    }

    private MonitorCidade() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        LabeAciA1 = new javax.swing.JLabel();
        LabeAgeA1 = new javax.swing.JLabel();
        LabeSomA1 = new javax.swing.JLabel();
        LabeFogoA1 = new javax.swing.JLabel();
        LabelLixoA1 = new javax.swing.JLabel();
        LabeChuvaA1 = new javax.swing.JLabel();
        LabeTempA1 = new javax.swing.JLabel();
        LabePolA1 = new javax.swing.JLabel();
        LabelCarroA1 = new javax.swing.JLabel();
        LabelSecQueA1 = new javax.swing.JLabel();
        LabelSolA1 = new javax.swing.JLabel();
        LabelNuvMovA1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Balao1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        LabelLixoA2 = new javax.swing.JLabel();
        LabeChuvaA2 = new javax.swing.JLabel();
        LabeSomA2 = new javax.swing.JLabel();
        LabeFogoA2 = new javax.swing.JLabel();
        LabeAciA2 = new javax.swing.JLabel();
        LabePolA2 = new javax.swing.JLabel();
        LabeTempA2 = new javax.swing.JLabel();
        LabeAgeA2 = new javax.swing.JLabel();
        LabelCarroA2 = new javax.swing.JLabel();
        LabelSecQueA2 = new javax.swing.JLabel();
        LabelNuvMovA2 = new javax.swing.JLabel();
        LabelSolA2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Balao2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        LabeAgeA4 = new javax.swing.JLabel();
        LabeTempA4 = new javax.swing.JLabel();
        LabelLixoA4 = new javax.swing.JLabel();
        LabeChuvaA4 = new javax.swing.JLabel();
        LabeSomA4 = new javax.swing.JLabel();
        LabeFogoA4 = new javax.swing.JLabel();
        LabeAciA4 = new javax.swing.JLabel();
        LabePolA4 = new javax.swing.JLabel();
        LabelCarroA4 = new javax.swing.JLabel();
        LabelSecQueA4 = new javax.swing.JLabel();
        LabelNuvMovA4 = new javax.swing.JLabel();
        LabelSolA4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Balao4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        LabelLixoA3 = new javax.swing.JLabel();
        LabeChuvaA3 = new javax.swing.JLabel();
        LabeSomA3 = new javax.swing.JLabel();
        LabeFogoA3 = new javax.swing.JLabel();
        LabeAciA3 = new javax.swing.JLabel();
        LabePolA3 = new javax.swing.JLabel();
        LabeTempA3 = new javax.swing.JLabel();
        LabeAgeA3 = new javax.swing.JLabel();
        LabelCarroA3 = new javax.swing.JLabel();
        LabelSecQueA3 = new javax.swing.JLabel();
        LabelNuvMovA3 = new javax.swing.JLabel();
        LabelSolA3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Balao3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        LabelCarroA5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monitor Ambiente");

        jPanel1.setLayout(null);

        jPanel2.setOpaque(false);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        LabeAciA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemAcida.png"))); // NOI18N
        jPanel5.add(LabeAciA1);
        LabeAciA1.setBounds(190, 20, 32, 35);

        LabeAgeA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/CaminhaoDesativado.png"))); // NOI18N
        jPanel5.add(LabeAgeA1);
        LabeAgeA1.setBounds(70, 60, 32, 32);

        LabeSomA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemBuzina.png"))); // NOI18N
        jPanel5.add(LabeSomA1);
        LabeSomA1.setBounds(90, 20, 60, 35);

        LabeFogoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemFogo.png"))); // NOI18N
        jPanel5.add(LabeFogoA1);
        LabeFogoA1.setBounds(150, 20, 32, 35);

        LabelLixoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoVazia.png"))); // NOI18N
        jPanel5.add(LabelLixoA1);
        LabelLixoA1.setBounds(10, 20, 32, 35);

        LabeChuvaA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemChuva.png"))); // NOI18N
        jPanel5.add(LabeChuvaA1);
        LabeChuvaA1.setBounds(50, 20, 32, 35);

        LabeTempA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp3.png"))); // NOI18N
        jPanel5.add(LabeTempA1);
        LabeTempA1.setBounds(10, 60, 50, 32);

        LabePolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado1.png"))); // NOI18N
        jPanel5.add(LabePolA1);
        LabePolA1.setBounds(230, 20, 32, 35);

        LabelCarroA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carroSem.png"))); // NOI18N
        jPanel5.add(LabelCarroA1);
        LabelCarroA1.setBounds(110, 60, 30, 30);

        LabelSecQueA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon-sem.png"))); // NOI18N
        jPanel5.add(LabelSecQueA1);
        LabelSecQueA1.setBounds(150, 60, 30, 30);

        LabelSolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Semsol.png"))); // NOI18N
        jPanel5.add(LabelSolA1);
        LabelSolA1.setBounds(190, 50, 32, 50);

        LabelNuvMovA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/no-wind-cloud.png"))); // NOI18N
        jPanel5.add(LabelNuvMovA1);
        LabelNuvMovA1.setBounds(230, 60, 40, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("1");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(310, 120, 10, 30);

        Balao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/balao_esq_sup (3).png"))); // NOI18N
        Balao1.setText("jLabel2");
        jPanel5.add(Balao1);
        Balao1.setBounds(0, 10, 350, 160);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, -20, 350, 200);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(null);

        LabelLixoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoVazia.png"))); // NOI18N
        jPanel8.add(LabelLixoA2);
        LabelLixoA2.setBounds(80, 50, 32, 32);

        LabeChuvaA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemChuva.png"))); // NOI18N
        jPanel8.add(LabeChuvaA2);
        LabeChuvaA2.setBounds(120, 50, 32, 32);

        LabeSomA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemBuzina.png"))); // NOI18N
        jPanel8.add(LabeSomA2);
        LabeSomA2.setBounds(160, 50, 60, 32);

        LabeFogoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemFogo.png"))); // NOI18N
        jPanel8.add(LabeFogoA2);
        LabeFogoA2.setBounds(220, 50, 32, 32);

        LabeAciA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemAcida.png"))); // NOI18N
        jPanel8.add(LabeAciA2);
        LabeAciA2.setBounds(260, 50, 32, 32);

        LabePolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado1.png"))); // NOI18N
        jPanel8.add(LabePolA2);
        LabePolA2.setBounds(300, 50, 32, 32);

        LabeTempA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp3.png"))); // NOI18N
        jPanel8.add(LabeTempA2);
        LabeTempA2.setBounds(80, 90, 50, 32);

        LabeAgeA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/CaminhaoDesativado.png"))); // NOI18N
        jPanel8.add(LabeAgeA2);
        LabeAgeA2.setBounds(140, 90, 32, 32);

        LabelCarroA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carroSem.png"))); // NOI18N
        jPanel8.add(LabelCarroA2);
        LabelCarroA2.setBounds(180, 90, 30, 30);

        LabelSecQueA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon-sem.png"))); // NOI18N
        jPanel8.add(LabelSecQueA2);
        LabelSecQueA2.setBounds(220, 90, 30, 30);

        LabelNuvMovA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/no-wind-cloud.png"))); // NOI18N
        jPanel8.add(LabelNuvMovA2);
        LabelNuvMovA2.setBounds(300, 90, 40, 30);

        LabelSolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Semsol.png"))); // NOI18N
        jPanel8.add(LabelSolA2);
        LabelSolA2.setBounds(260, 80, 32, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText(" 2");
        jPanel8.add(jLabel5);
        jLabel5.setBounds(20, 150, 30, 20);

        Balao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/balao_dir_sup (3).png"))); // NOI18N
        jPanel8.add(Balao2);
        Balao2.setBounds(0, 0, 350, 230);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(0, 70, 370, 230);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(450, 80, 360, 270);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(null);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(null);

        LabeAgeA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/CaminhaoDesativado.png"))); // NOI18N
        jPanel10.add(LabeAgeA4);
        LabeAgeA4.setBounds(90, 180, 32, 32);

        LabeTempA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp3.png"))); // NOI18N
        jPanel10.add(LabeTempA4);
        LabeTempA4.setBounds(30, 180, 50, 32);

        LabelLixoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoVazia.png"))); // NOI18N
        jPanel10.add(LabelLixoA4);
        LabelLixoA4.setBounds(30, 140, 32, 32);

        LabeChuvaA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemChuva.png"))); // NOI18N
        jPanel10.add(LabeChuvaA4);
        LabeChuvaA4.setBounds(70, 140, 32, 32);

        LabeSomA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemBuzina.png"))); // NOI18N
        jPanel10.add(LabeSomA4);
        LabeSomA4.setBounds(110, 140, 60, 32);

        LabeFogoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemFogo.png"))); // NOI18N
        jPanel10.add(LabeFogoA4);
        LabeFogoA4.setBounds(170, 140, 32, 32);

        LabeAciA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemAcida.png"))); // NOI18N
        jPanel10.add(LabeAciA4);
        LabeAciA4.setBounds(210, 140, 32, 32);

        LabePolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado1.png"))); // NOI18N
        jPanel10.add(LabePolA4);
        LabePolA4.setBounds(250, 140, 32, 32);

        LabelCarroA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carroSem.png"))); // NOI18N
        jPanel10.add(LabelCarroA4);
        LabelCarroA4.setBounds(130, 180, 30, 30);

        LabelSecQueA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon-sem.png"))); // NOI18N
        jPanel10.add(LabelSecQueA4);
        LabelSecQueA4.setBounds(170, 180, 30, 30);

        LabelNuvMovA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/no-wind-cloud.png"))); // NOI18N
        jPanel10.add(LabelNuvMovA4);
        LabelNuvMovA4.setBounds(250, 180, 40, 30);

        LabelSolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Semsol.png"))); // NOI18N
        jPanel10.add(LabelSolA4);
        LabelSolA4.setBounds(210, 170, 32, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("4");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(320, 80, 20, 30);

        Balao4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/balao_esq_inf (3).png"))); // NOI18N
        jPanel10.add(Balao4);
        Balao4.setBounds(10, 60, 350, 170);

        jPanel6.add(jPanel10);
        jPanel10.setBounds(-10, 30, 460, 270);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 270, 470, 260);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(null);

        LabelLixoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoVazia.png"))); // NOI18N
        jPanel9.add(LabelLixoA3);
        LabelLixoA3.setBounds(70, 150, 32, 32);

        LabeChuvaA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemChuva.png"))); // NOI18N
        jPanel9.add(LabeChuvaA3);
        LabeChuvaA3.setBounds(110, 150, 32, 32);

        LabeSomA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemBuzina.png"))); // NOI18N
        jPanel9.add(LabeSomA3);
        LabeSomA3.setBounds(150, 150, 60, 32);

        LabeFogoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemFogo.png"))); // NOI18N
        jPanel9.add(LabeFogoA3);
        LabeFogoA3.setBounds(210, 150, 32, 32);

        LabeAciA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemAcida.png"))); // NOI18N
        jPanel9.add(LabeAciA3);
        LabeAciA3.setBounds(250, 150, 32, 32);

        LabePolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado1.png"))); // NOI18N
        jPanel9.add(LabePolA3);
        LabePolA3.setBounds(290, 150, 32, 32);

        LabeTempA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp3.png"))); // NOI18N
        jPanel9.add(LabeTempA3);
        LabeTempA3.setBounds(70, 190, 50, 32);

        LabeAgeA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/CaminhaoDesativado.png"))); // NOI18N
        jPanel9.add(LabeAgeA3);
        LabeAgeA3.setBounds(130, 190, 32, 32);

        LabelCarroA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carroSem.png"))); // NOI18N
        jPanel9.add(LabelCarroA3);
        LabelCarroA3.setBounds(170, 190, 30, 30);

        LabelSecQueA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon-sem.png"))); // NOI18N
        jPanel9.add(LabelSecQueA3);
        LabelSecQueA3.setBounds(210, 190, 30, 30);

        LabelNuvMovA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/no-wind-cloud.png"))); // NOI18N
        jPanel9.add(LabelNuvMovA3);
        LabelNuvMovA3.setBounds(290, 190, 40, 30);

        LabelSolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Semsol.png"))); // NOI18N
        jPanel9.add(LabelSolA3);
        LabelSolA3.setBounds(250, 180, 32, 50);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText(" 3");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(20, 90, 20, 30);

        Balao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/balao_dir_inf (3).png"))); // NOI18N
        jPanel9.add(Balao3);
        Balao3.setBounds(0, 40, 450, 227);

        jPanel4.add(jPanel9);
        jPanel9.setBounds(140, 20, 370, 270);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(310, 330, 480, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/mapa_final_final.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, -10, 806, 600);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Legenda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DECODE", 0, 36))); // NOI18N

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Caminhao.png"))); // NOI18N
        jLabel47.setText("Coleta de Lixo");

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp5.png"))); // NOI18N
        jLabel48.setText("Temperatura");

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoEnchendo.png"))); // NOI18N
        jLabel49.setText("Lixeira");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemChuva.png"))); // NOI18N
        jLabel50.setText("Chuva");

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Buzina.png"))); // NOI18N
        jLabel51.setText("Poluição Sonora");

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Fogo.png"))); // NOI18N
        jLabel52.setText("Fogo");

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemAcida.png"))); // NOI18N
        jLabel53.setText("Chuva Ácida");

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado6.png"))); // NOI18N
        jLabel54.setText("Poluição do Ar");

        LabelCarroA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carro.png"))); // NOI18N
        LabelCarroA5.setText("Carros");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon.png"))); // NOI18N
        jLabel6.setText("Quente e Seco");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/sol.png"))); // NOI18N
        jLabel2.setText("Tempo Bom");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel49)
                        .addComponent(jLabel48)
                        .addComponent(jLabel53)
                        .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel52)
                        .addComponent(jLabel50)
                        .addComponent(jLabel47)
                        .addComponent(jLabel54)
                        .addComponent(LabelCarroA5)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addGap(4, 4, 4)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCarroA5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(810, 40, 144, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MonitorCidade().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balao1;
    private javax.swing.JLabel Balao2;
    private javax.swing.JLabel Balao3;
    private javax.swing.JLabel Balao4;
    private javax.swing.JLabel LabeAciA1;
    private javax.swing.JLabel LabeAciA2;
    private javax.swing.JLabel LabeAciA3;
    private javax.swing.JLabel LabeAciA4;
    private javax.swing.JLabel LabeAgeA1;
    private javax.swing.JLabel LabeAgeA2;
    private javax.swing.JLabel LabeAgeA3;
    private javax.swing.JLabel LabeAgeA4;
    private javax.swing.JLabel LabeChuvaA1;
    private javax.swing.JLabel LabeChuvaA2;
    private javax.swing.JLabel LabeChuvaA3;
    private javax.swing.JLabel LabeChuvaA4;
    private javax.swing.JLabel LabeFogoA1;
    private javax.swing.JLabel LabeFogoA2;
    private javax.swing.JLabel LabeFogoA3;
    private javax.swing.JLabel LabeFogoA4;
    private javax.swing.JLabel LabePolA1;
    private javax.swing.JLabel LabePolA2;
    private javax.swing.JLabel LabePolA3;
    private javax.swing.JLabel LabePolA4;
    private javax.swing.JLabel LabeSomA1;
    private javax.swing.JLabel LabeSomA2;
    private javax.swing.JLabel LabeSomA3;
    private javax.swing.JLabel LabeSomA4;
    private javax.swing.JLabel LabeTempA1;
    private javax.swing.JLabel LabeTempA2;
    private javax.swing.JLabel LabeTempA3;
    private javax.swing.JLabel LabeTempA4;
    private javax.swing.JLabel LabelCarroA1;
    private javax.swing.JLabel LabelCarroA2;
    private javax.swing.JLabel LabelCarroA3;
    private javax.swing.JLabel LabelCarroA4;
    private javax.swing.JLabel LabelCarroA5;
    private javax.swing.JLabel LabelLixoA1;
    private javax.swing.JLabel LabelLixoA2;
    private javax.swing.JLabel LabelLixoA3;
    private javax.swing.JLabel LabelLixoA4;
    private javax.swing.JLabel LabelNuvMovA1;
    private javax.swing.JLabel LabelNuvMovA2;
    private javax.swing.JLabel LabelNuvMovA3;
    private javax.swing.JLabel LabelNuvMovA4;
    private javax.swing.JLabel LabelSecQueA1;
    private javax.swing.JLabel LabelSecQueA2;
    private javax.swing.JLabel LabelSecQueA3;
    private javax.swing.JLabel LabelSecQueA4;
    private javax.swing.JLabel LabelSolA1;
    private javax.swing.JLabel LabelSolA2;
    private javax.swing.JLabel LabelSolA3;
    private javax.swing.JLabel LabelSolA4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    //POLLUTION MONITOR
    @Override
    public void atualizaNivelPoluicao(Integer area, String levelPollution) {
        //levelPollution= BOA, REGULAR, INADEQUADA, MA, PESSIMA
        if (area.equals(1)) {
            if (levelPollution.equals("BOA")) {
                LabePolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado1.png")));
                //setar o icone pra boa
            } else if (levelPollution.equals("REGULAR")) {
                LabePolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado2.png")));
                //setar icone pra regular
            } else if (levelPollution.equals("INADEQUADA")) {
                LabePolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado3.png")));
                //setar icone pra inadequada
            } else if (levelPollution.equals("MA")) {
                LabePolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado4.png")));
                //setar icone pra ma
            } else if (levelPollution.equals("PESSIMA")) {
                LabePolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado5.png")));
                //setar icone pra pessima
            }

        } else if (area.equals(2)) {
            if (levelPollution.equals("BOA")) {
                LabePolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado1.png")));
                //setar o icone pra boa
            } else if (levelPollution.equals("REGULAR")) {
                LabePolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado2.png")));
                //setar icone pra regular
            } else if (levelPollution.equals("INADEQUADA")) {
                LabePolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado3.png")));
                //setar icone pra inadequada
            } else if (levelPollution.equals("MA")) {
                LabePolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado4.png")));
                //setar icone pra ma
            } else if (levelPollution.equals("PESSIMA")) {
                LabePolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado5.png")));
                //setar icone pra pessima
            }
        } else if (area.equals(3)) {
            if (levelPollution.equals("BOA")) {
                LabePolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado1.png")));
                //setar o icone pra boa
            } else if (levelPollution.equals("REGULAR")) {
                LabePolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado2.png")));
                //setar icone pra regular
            } else if (levelPollution.equals("INADEQUADA")) {
                LabePolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado3.png")));
                //setar icone pra inadequada
            } else if (levelPollution.equals("MA")) {
                LabePolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado4.png")));
                //setar icone pra ma
            } else if (levelPollution.equals("PESSIMA")) {
                LabePolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado5.png")));
                //setar icone pra pessima
            }
        } else if (area.equals(4)) {
            if (levelPollution.equals("BOA")) {
                LabePolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado1.png")));
                //setar o icone pra boa
            } else if (levelPollution.equals("REGULAR")) {
                LabePolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado2.png")));
                //setar icone pra regular
            } else if (levelPollution.equals("INADEQUADA")) {
                LabePolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado3.png")));
                //setar icone pra inadequada
            } else if (levelPollution.equals("MA")) {
                LabePolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado4.png")));
                //setar icone pra ma
            } else if (levelPollution.equals("PESSIMA")) {
                LabePolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemVerdeEstado5.png")));
                //setar icone pra pessima
            }
        }
    }

    @Override
    public void atualizaFluxoVeiculos(Integer area, String vehicleFlow) {
        //vehicleFlow = TRAFEGO_ON, TRAFEGO_OFF
        if (area.equals(1)) {
            if (vehicleFlow.equals("TRAFEGO_ON")) {
                LabelCarroA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/carro.png")));
                //seta icone ligado
            } else if (vehicleFlow.equals("TRAFEGO_OFF")) {
                LabelCarroA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/carroSem.png")));
                //seta icone OFF
            }
        } else if (area.equals(2)) {
            if (vehicleFlow.equals("TRAFEGO_ON")) {
                LabelCarroA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/carro.png")));
                //seta icone ligado
            } else if (vehicleFlow.equals("TRAFEGO_OFF")) {
                LabelCarroA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/carroSem.png")));
                //seta icone OFF
            }
        } else if (area.equals(3)) {
            if (vehicleFlow.equals("TRAFEGO_ON")) {
                LabelCarroA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/carro.png")));
                //seta icone ligado
            } else if (vehicleFlow.equals("TRAFEGO_OFF")) {
                LabelCarroA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/carroSem.png")));
                //seta icone OFF
            }
        } else if (area.equals(4)) {
            if (vehicleFlow.equals("TRAFEGO_ON")) {
                LabelCarroA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/carro.png")));
                //seta icone ligado
            } else if (vehicleFlow.equals("TRAFEGO_OFF")) {
                LabelCarroA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/carroSem.png")));
                //seta icone OFF
            }
        }
    }

    @Override
    public void atualizaProbabilidaDeChuva(Integer area, String willRain) {
        //willRain = RAIN_ON ou RAIN_OFF
        if (area.equals(1)) {
            if (willRain.equals("RAIN_ON")) {
                LabeChuvaA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemChuva.png")));
                //seta icone ligado
            } else if (willRain.equals("RAIN_OFF")) {
                LabeChuvaA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemSemChuva.png")));
                //seta icone OFF
            }
        } else if (area.equals(2)) {
            if (willRain.equals("RAIN_ON")) {
                LabeChuvaA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemChuva.png")));
                //seta icone ligado
            } else if (willRain.equals("RAIN_OFF")) {
                LabeChuvaA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemSemChuva.png")));
                //seta icone OFF
            }
        } else if (area.equals(3)) {
            if (willRain.equals("RAIN_ON")) {
                LabeChuvaA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemChuva.png")));
                //seta icone ligado
            } else if (willRain.equals("RAIN_OFF")) {
                LabeChuvaA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemSemChuva.png")));
                //seta icone OFF
            }
        } else if (area.equals(4)) {
            if (willRain.equals("RAIN_ON")) {
                LabeChuvaA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemChuva.png")));
                //seta icone ligado
            } else if (willRain.equals("RAIN_OFF")) {
                LabeChuvaA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemSemChuva.png")));
                //seta icone OFF
            }
        }
    }

    @Override
    public void atualizaChuvaAcida(Integer area, String localAcidRain, String directionWind) {
        //localAcidRain = AQUI, OUTRO, ACID_OFF
        if (area.equals(1)) {
            if (localAcidRain.equals("AQUI")) {
                LabeAciA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemAcida.png")));
                //seta icone chuva acida na mesma area
            } else if (localAcidRain.equals("OUTRO")) {
                LabelNuvMovA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/wind-cloud.png")));
                //seta icone chuva acida que vai pra outra area e usar a directionWind pra informar pra que lado ela está indo
            } else if (localAcidRain.equals("ACID_OFF")) {
                LabeAciA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemSemAcida.png")));
                LabelNuvMovA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/no-wind-cloud.png")));
                //seta icone chuva acida OFF
            }
        } else if (area.equals(2)) {
            if (localAcidRain.equals("AQUI")) {
                LabeAciA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemAcida.png")));
                //seta icone chuva acida na mesma area
            } else if (localAcidRain.equals("OUTRO")) {
                LabelNuvMovA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/wind-cloud.png")));
                //seta icone chuva acida que vai pra outra area e usar a directionWind pra informar pra que lado ela está indo
            } else if (localAcidRain.equals("ACID_OFF")) {
                LabeAciA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemSemAcida.png")));
                LabelNuvMovA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/no-wind-cloud.png")));
                //seta icone chuva acida OFF
            }
        } else if (area.equals(3)) {
            if (localAcidRain.equals("AQUI")) {
                LabeAciA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemAcida.png")));
                //seta icone chuva acida na mesma area
            } else if (localAcidRain.equals("OUTRO")) {
                LabelNuvMovA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/wind-cloud.png")));
                //seta icone chuva acida que vai pra outra area e usar a directionWind pra informar pra que lado ela está indo
            } else if (localAcidRain.equals("ACID_OFF")) {
                LabeAciA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemSemAcida.png")));
                LabelNuvMovA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/no-wind-cloud.png")));
                //seta icone chuva acida OFF
            }
        } else if (area.equals(4)) {
            if (localAcidRain.equals("AQUI")) {
                LabeAciA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemAcida.png")));
                //seta icone chuva acida na mesma area
            } else if (localAcidRain.equals("OUTRO")) {
                LabelNuvMovA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/wind-cloud.png")));
                //seta icone chuva acida que vai pra outra area e usar a directionWind pra informar pra que lado ela está indo
            } else if (localAcidRain.equals("ACID_OFF")) {
                LabeAciA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/NuvemSemAcida.png")));
                LabelNuvMovA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/no-wind-cloud.png")));
                //seta icone chuva acida OFF
            }
        }
    }

    @Override
    public void atualizaQuantidadeRuido(Integer area, String noise, Integer db) {
        DateFormat df = new SimpleDateFormat("H");
        String hora = df.format(new Date());
        
        //noise = NOISE_ON, NOISE_OFF
        if (area.equals(1)) {
            if (noise.equals("NOISE_ON")) {
                if ((Integer.parseInt(hora) >= 22 && Integer.parseInt(hora) <= 24) || (Integer.parseInt(hora) >= 0 && Integer.parseInt(hora) < 6)) {
                    LabeSomA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Buzina.png")));
                    LabeSomA1.setText("" + db);
                    //verificar a hora atual e ver se esta em horario inadequado, se SIM, setar o icone
                }
            } else if (noise.equals("NOISE_OFF")) {
                LabeSomA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/SemBuzina.png")));
                //setar icone OFF
            }
        } else if (area.equals(2)) {
            if (noise.equals("NOISE_ON")) {
                if ((Integer.parseInt(hora) >= 22 && Integer.parseInt(hora) <= 24) || (Integer.parseInt(hora) >= 0 && Integer.parseInt(hora) < 6)) {
                    LabeSomA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Buzina.png")));
                    LabeSomA2.setText("" + db);
                    //verificar a hora atual e ver se esta em horario inadequado, se SIM, setar o icone
                }
            } else if (noise.equals("NOISE_OFF")) {
                LabeSomA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/SemBuzina.png")));
                //setar icone OFF
            }
        } else if (area.equals(3)) {
            if (noise.equals("NOISE_ON")) {
                if ((Integer.parseInt(hora) >= 22 && Integer.parseInt(hora) <= 24) || (Integer.parseInt(hora) >= 0 && Integer.parseInt(hora) < 6)) {
                    LabeSomA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Buzina.png")));
                    LabeSomA3.setText("" + db);
                    //verificar a hora atual e ver se esta em horario inadequado, se SIM, setar o icone
                }
            } else if (noise.equals("NOISE_OFF")) {
                LabeSomA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/SemBuzina.png")));
                //setar icone OFF
            }
        } else if (area.equals(4)) {
            if (noise.equals("NOISE_ON")) {
                if ((Integer.parseInt(hora) >= 22 && Integer.parseInt(hora) <= 24) || (Integer.parseInt(hora) >= 0 && Integer.parseInt(hora) < 6)) {
                    LabeSomA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Buzina.png")));
                    LabeSomA4.setText("" + db);
                    //verificar a hora atual e ver se esta em horario inadequado, se SIM, setar o icone
                }
            } else if (noise.equals("NOISE_OFF")) {
                LabeSomA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/SemBuzina.png")));
                //setar icone OFF
            }
        }
    }

    //TEMPERATURE MONITOR
    @Override
    public void atualizaTemperatura(Integer area, Integer temperature) {
        if (area.equals(1)) {
            LabeTempA1.setText("" + temperature);
            if (temperature <= 10) {
                LabeTempA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp1.png")));
                LabeTempA1.setText("" + temperature);
            } else if (temperature > 10 && temperature <= 20) {
                LabeTempA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp2.png")));
                LabeTempA1.setText("" + temperature);
            } else if (temperature > 20 && temperature <= 30) {
                LabeTempA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp3.png")));
                LabeTempA1.setText("" + temperature);
            } else if (temperature > 30 && temperature <= 40) {
                LabeTempA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp4.png")));
                LabeTempA1.setText("" + temperature);
            } else if (temperature > 40) {
                LabeTempA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp5.png")));
                LabeTempA1.setText("" + temperature);
            }
            //seta icone ligado e mostrar o valor da temperatura
        } else if (area.equals(2)) {
            LabeTempA2.setText("" + temperature);
            if (temperature <= 10) {
                LabeTempA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp1.png")));
                LabeTempA2.setText("" + temperature);
            } else if (temperature > 10 && temperature <= 20) {
                LabeTempA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp2.png")));
                LabeTempA2.setText("" + temperature);
            } else if (temperature > 20 && temperature <= 30) {
                LabeTempA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp3.png")));
                LabeTempA2.setText("" + temperature);
            } else if (temperature > 30 && temperature <= 40) {
                LabeTempA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp4.png")));
                LabeTempA2.setText("" + temperature);
            } else if (temperature > 40) {
                LabeTempA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp5.png")));
                LabeTempA2.setText("" + temperature);
            }
            //seta icone ligado e mostrar o valor da temperatura
        } else if (area.equals(3)) {
            LabeTempA2.setText("" + temperature);
            if (temperature <= 10) {
                LabeTempA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp1.png")));
                LabeTempA3.setText("" + temperature);
            } else if (temperature > 10 && temperature <= 20) {
                LabeTempA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp2.png")));
                LabeTempA3.setText("" + temperature);
            } else if (temperature > 20 && temperature <= 30) {
                LabeTempA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp3.png")));
                LabeTempA3.setText("" + temperature);
            } else if (temperature > 30 && temperature <= 40) {
                LabeTempA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp4.png")));
                LabeTempA3.setText("" + temperature);
            } else if (temperature > 40) {
                LabeTempA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp5.png")));
                LabeTempA3.setText("" + temperature);
            }
            //seta icone ligado e mostrar o valor da temperatura
        } else if (area.equals(4)) {
            LabeTempA4.setText("" + temperature);
            if (temperature <= 10) {
                LabeTempA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp1.png")));
                LabeTempA4.setText("" + temperature);
            } else if (temperature > 10 && temperature <= 20) {
                LabeTempA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp2.png")));
                LabeTempA4.setText("" + temperature);
            } else if (temperature > 20 && temperature <= 30) {
                LabeTempA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp3.png")));
                LabeTempA4.setText("" + temperature);
            } else if (temperature > 30 && temperature <= 40) {
                LabeTempA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp4.png")));
                LabeTempA4.setText("" + temperature);
            } else if (temperature > 40) {
                LabeTempA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/temp5.png")));
                LabeTempA4.setText("" + temperature);
            }
            //seta icone ligado e mostrar o valor da temperatura
        }
    }

    @Override
    public void atualizaClimaBom(Integer area, String clima) {
        //
        if (area.equals(1)) {
            if (clima.equals("BEAUTIFUL_ON")) {
                LabelSolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/sol.png")));
                //seta icone ligado
            } else if (clima.equals("BEAUTIFUL_OFF")){
                LabelSolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Semsol.png")));
            }
        } else if (area.equals(2)) {
            if (clima.equals("BEAUTIFUL_ON")) {
                LabelSolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/sol.png")));
                //seta icone ligado
            } else if (clima.equals("BEAUTIFUL_OFF")){
                LabelSolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Semsol.png")));
            }
        } else if (area.equals(3)) {
            if (clima.equals("BEAUTIFUL_ON")) {
                LabelSolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/sol.png")));
                //seta icone ligado
            } else if (clima.equals("BEAUTIFUL_OFF")){
                LabelSolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Semsol.png")));
            }
        } else if (area.equals(4)) {
            if (clima.equals("BEAUTIFUL_ON")) {
                LabelSolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/sol.png")));
                //seta icone ligado
            } else if (clima.equals("BEAUTIFUL_OFF")){
                LabelSolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Semsol.png")));
            }
        }
    }

    @Override
    public void atualizaIncidenciaDeIncendio(Integer area, String isFire) {
        //
        if (area.equals(1)) {
            if (isFire.equals("FIRE_ON")) {
                LabeFogoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Fogo.png")));
                //seta icone ligado
            } else  if (isFire.equals("FIRE_OFF")){
                LabeFogoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/SemFogo.png")));
            }
        } else if (area.equals(2)) {
            if (isFire.equals("FIRE_ON")) {
                LabeFogoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Fogo.png")));
                //seta icone ligado
            } else if (isFire.equals("FIRE_OFF")){
                LabeFogoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/SemFogo.png")));
            }
        } else if (area.equals(3)) {
            if (isFire.equals("FIRE_ON")) {
                LabeFogoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Fogo.png")));
                //seta icone ligado
            } else if (isFire.equals("FIRE_OFF")){
                LabeFogoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/SemFogo.png")));
            }
        } else if (area.equals(4)) {
            if (isFire.equals("FIRE_ON")) {
                LabeFogoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Fogo.png")));
                //seta icone ligado
            } else if (isFire.equals("FIRE_OFF")){
                LabeFogoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/SemFogo.png")));
            }
        }
    }

    @Override
    public void atualizaClimaQuenteESeco(Integer area, String hotDry) {
        //
        if (area.equals(1)) {
            if (hotDry.equals("HOTDRY_ON")) {
                LabelSecQueA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/eyes-on-fire-icon.png")));
                //seta icone ligado
            } else if (hotDry.equals("HOTDRY_OFF")){
                LabelSecQueA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/eyes-on-fire-icon-sem.png")));
            }
        } else if (area.equals(2)) {
            if (hotDry.equals("HOTDRY_ON")) {
                LabelSecQueA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/eyes-on-fire-icon.png")));
                //seta icone ligado
            } else if (hotDry.equals("HOTDRY_OFF")){
                LabelSecQueA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/eyes-on-fire-icon-sem.png")));
            }
        } else if (area.equals(3)) {
            if (hotDry.equals("HOTDRY_ON")) {
                LabelSecQueA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon.png")));
                //seta icone ligado
            } else if (hotDry.equals("HOTDRY_OFF")){
                LabelSecQueA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/eyes-on-fire-icon-sem.png")));
            }
        } else if (area.equals(4)) {
            if (hotDry.equals("HOTDRY_ON")) {
                LabelSecQueA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/eyes-on-fire-icon.png")));
                //seta icone ligado
            } else if (hotDry.equals("HOTDRY_OFF")){
                LabelSecQueA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/eyes-on-fire-icon-sem.png")));
            }
        }
    }

    //DUMP MONITOR
    @Override
    public void atualizaQuantidadeLixo(Integer area, String content) {
        //
        if (area.equals(1)) {
            if (content.equals("VAZIA")) {
                LabelLixoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoVazia.png")));
                //seta icone vazia
            } else if (content.equals("ENCHENDO")) {
                LabelLixoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoEnchendo.png")));
                //seta icone enchendo
            } else if (content.equals("CHEIA")) {
                LabelLixoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoCheio.png")));
                //seta icone cheia
            }
        } else if (area.equals(2)) {
            if (content.equals("VAZIA")) {
                LabelLixoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoVazia.png")));
                //seta icone vazia
            } else if (content.equals("ENCHENDO")) {
                LabelLixoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoEnchendo.png")));
                //seta icone enchendo
            } else if (content.equals("CHEIA")) {
                LabelLixoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoCheio.png")));
                //seta icone cheia
            }
        } else if (area.equals(3)) {
            if (content.equals("VAZIA")) {
                LabelLixoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoVazia.png")));
                //seta icone vazia
            } else if (content.equals("ENCHENDO")) {
                LabelLixoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoEnchendo.png")));
                //seta icone enchendo
            } else if (content.equals("CHEIA")) {
                LabelLixoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoCheio.png")));
                //seta icone cheia
            }
        } else if (area.equals(4)) {
            if (content.equals("VAZIA")) {
                LabelLixoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoVazia.png")));
                //seta icone vazia
            } else if (content.equals("ENCHENDO")) {
                LabelLixoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoEnchendo.png")));
                //seta icone enchendo
            } else if (content.equals("CHEIA")) {
                LabelLixoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoCheio.png")));
                //seta icone cheia
            }
        }
    }

    @Override
    public void atualizaAgenteProximo(Integer area, String status, String agentNearName, Integer agentDistance) {
        //status= LIMITE, GATHERING_ON, GATHERING_OFF
        if (area.equals(1)) {
            if (status.equals("LIMITE")) {
                LabelLixoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoEnchendoLimite.png")));
                LabeAgeA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Caminhao.png")));
                //seta icone limite e avisar que esta no limite
            } else if (status.equals("GATHERING_ON")) {
                LabelLixoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoVazia.png")));
                LabeAgeA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/CaminhaoDesativado.png")));
                //seta o icone de cheia e diz que chamou o agente
            } else if (status.equals("GATHERING_OFF")) {
                LabeAgeA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/CaminhaoDesativado.png")));
                //setar o icone OFF do agente
            }
        } else if (area.equals(2)) {
            if (status.equals("LIMITE")) {
                LabelLixoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoEnchendoLimite.png")));
                LabeAgeA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Caminhao.png")));
                //seta icone limite e avisar que esta no limite
            } else if (status.equals("GATHERING_ON")) {
                LabelLixoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoVazia.png")));
                LabeAgeA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/CaminhaoDesativado.png")));
                //seta o icone de cheia e diz que chamou o agente
            } else if (status.equals("GATHERING_OFF")) {
                LabeAgeA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/CaminhaoDesativado.png")));
                //setar o icone OFF do agente
            }
        } else if (area.equals(3)) {
            if (status.equals("LIMITE")) {
                LabelLixoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoEnchendoLimite.png")));
                LabeAgeA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Caminhao.png")));
                //seta icone limite e avisar que esta no limite
            } else if (status.equals("GATHERING_ON")) {
                LabelLixoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoVazia.png")));
                LabeAgeA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/CaminhaoDesativado.png")));
                //seta o icone de cheia e diz que chamou o agente
            } else if (status.equals("GATHERING_OFF")) {
                LabeAgeA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/CaminhaoDesativado.png")));
                //setar o icone OFF do agente
            }
        } else if (area.equals(4)) {
            if (status.equals("LIMITE")) {
                LabelLixoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoEnchendoLimite.png")));
                LabeAgeA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/Caminhao.png")));
                //seta icone limite e avisar que esta no limite
            } else if (status.equals("GATHERING_ON")) {
                LabelLixoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/LixoVazia.png")));
                LabeAgeA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/CaminhaoDesativado.png")));
                //seta o icone de cheia e diz que chamou o agente
            } else if (status.equals("GATHERING_OFF")) {
                LabeAgeA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/imagens/CaminhaoDesativado.png")));
                //setar o icone OFF do agente
            }
        }
    }

}    //fim :p

